### PR TITLE
fixing some html [skip ci]

### PR DESCRIPTION
**Pull request by debpaul**
the table needs styling.

Issues.
1. do we have any css styling for tables?
2. adjusting the width of the table (not too wide b/c it's harder to read). and hard to preview using github
3. need to fix the call to the "data-utc-to-local" function (see header row)

### CODE REVIEW

**Comment by jlpereira** [comment]
@debpaul this site use Bootstrap, if you want to apply css style for tables you can take a look here: https://getbootstrap.com/docs/4.0/content/tables/

For width sizes: https://getbootstrap.com/docs/4.0/utilities/sizing/

**Comment by debpaul** [comment]
> @debpaul this site use Bootstrap, if you want to apply css style for tables you can take a look here: https://getbootstrap.com/docs/4.0/content/tables/
> 
> For width sizes: https://getbootstrap.com/docs/4.0/utilities/sizing/

Yes @jlpereira I did add a table width constraint and fixed the < > but not sure if this is all that's needed to have this table look good once we commit. Any other tweaks? And will the function to convert UTC to local work now after the <> fix?

**Comment by jlpereira** [comment]
> > @debpaul this site use Bootstrap, if you want to apply css style for tables you can take a look here: https://getbootstrap.com/docs/4.0/content/tables/
> > For width sizes: https://getbootstrap.com/docs/4.0/utilities/sizing/
> 
> Yes @jlpereira I did add a table width constraint and fixed the < > but not sure if this is all that's needed to have this table look good once we commit. Any other tweaks? And will the function to convert UTC to local work now after the <> fix?

Yah, it should works after fixing <>. I will take a look the table issue

**Comment by debpaul** [comment]
Looks good to me now @jlpereira. I think I can merge now and we'll have a look-see. Thanks!

**Pull request merged**
